version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.17.5
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'npm install'
      - run:
          name: Dependencias
          command: npm install
      - run:
          name: Instalando dependencias
          command: CI=false npm run build
  test:
    docker:
      - image: circleci/node:14.17.5
    steps:
      - checkout
      - run: echo 'npm test'
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: circleci/node:14.17.5
    steps:
      - checkout
      - run: echo "Completado vieja"
workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
