version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - run:
          name: The First Step
          command: |
            echo 'npm install'
      - run:
          name: Dependencias
          command: npm install
      - run:
          name: Instalando dependencias
          command: CI=true npm run build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - run: echo 'npm test'
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Completado vieja"
workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - hithere
      - test:
        requires:
          - hithere
